// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mapper.proto
#ifndef GRPC_mapper_2eproto__INCLUDED
#define GRPC_mapper_2eproto__INCLUDED

#include "mapper.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace mapper {

// Defines the service
class Mapper final {
 public:
  static constexpr char const* service_full_name() {
    return "mapper.Mapper";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Function invoked to send the request
    virtual ::grpc::Status start_mapper(::grpc::ClientContext* context, const ::mapper::MapperRequest& request, ::mapper::MapperReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapper::MapperReply>> Asyncstart_mapper(::grpc::ClientContext* context, const ::mapper::MapperRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapper::MapperReply>>(Asyncstart_mapperRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapper::MapperReply>> PrepareAsyncstart_mapper(::grpc::ClientContext* context, const ::mapper::MapperRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mapper::MapperReply>>(PrepareAsyncstart_mapperRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Function invoked to send the request
      virtual void start_mapper(::grpc::ClientContext* context, const ::mapper::MapperRequest* request, ::mapper::MapperReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void start_mapper(::grpc::ClientContext* context, const ::mapper::MapperRequest* request, ::mapper::MapperReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mapper::MapperReply>* Asyncstart_mapperRaw(::grpc::ClientContext* context, const ::mapper::MapperRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mapper::MapperReply>* PrepareAsyncstart_mapperRaw(::grpc::ClientContext* context, const ::mapper::MapperRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status start_mapper(::grpc::ClientContext* context, const ::mapper::MapperRequest& request, ::mapper::MapperReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapper::MapperReply>> Asyncstart_mapper(::grpc::ClientContext* context, const ::mapper::MapperRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapper::MapperReply>>(Asyncstart_mapperRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapper::MapperReply>> PrepareAsyncstart_mapper(::grpc::ClientContext* context, const ::mapper::MapperRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mapper::MapperReply>>(PrepareAsyncstart_mapperRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void start_mapper(::grpc::ClientContext* context, const ::mapper::MapperRequest* request, ::mapper::MapperReply* response, std::function<void(::grpc::Status)>) override;
      void start_mapper(::grpc::ClientContext* context, const ::mapper::MapperRequest* request, ::mapper::MapperReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mapper::MapperReply>* Asyncstart_mapperRaw(::grpc::ClientContext* context, const ::mapper::MapperRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mapper::MapperReply>* PrepareAsyncstart_mapperRaw(::grpc::ClientContext* context, const ::mapper::MapperRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_start_mapper_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Function invoked to send the request
    virtual ::grpc::Status start_mapper(::grpc::ServerContext* context, const ::mapper::MapperRequest* request, ::mapper::MapperReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_start_mapper : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_start_mapper() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_start_mapper() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status start_mapper(::grpc::ServerContext* /*context*/, const ::mapper::MapperRequest* /*request*/, ::mapper::MapperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requeststart_mapper(::grpc::ServerContext* context, ::mapper::MapperRequest* request, ::grpc::ServerAsyncResponseWriter< ::mapper::MapperReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_start_mapper<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_start_mapper : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_start_mapper() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::mapper::MapperRequest, ::mapper::MapperReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mapper::MapperRequest* request, ::mapper::MapperReply* response) { return this->start_mapper(context, request, response); }));}
    void SetMessageAllocatorFor_start_mapper(
        ::grpc::MessageAllocator< ::mapper::MapperRequest, ::mapper::MapperReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mapper::MapperRequest, ::mapper::MapperReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_start_mapper() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status start_mapper(::grpc::ServerContext* /*context*/, const ::mapper::MapperRequest* /*request*/, ::mapper::MapperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* start_mapper(
      ::grpc::CallbackServerContext* /*context*/, const ::mapper::MapperRequest* /*request*/, ::mapper::MapperReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_start_mapper<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_start_mapper : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_start_mapper() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_start_mapper() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status start_mapper(::grpc::ServerContext* /*context*/, const ::mapper::MapperRequest* /*request*/, ::mapper::MapperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_start_mapper : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_start_mapper() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_start_mapper() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status start_mapper(::grpc::ServerContext* /*context*/, const ::mapper::MapperRequest* /*request*/, ::mapper::MapperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requeststart_mapper(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_start_mapper : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_start_mapper() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->start_mapper(context, request, response); }));
    }
    ~WithRawCallbackMethod_start_mapper() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status start_mapper(::grpc::ServerContext* /*context*/, const ::mapper::MapperRequest* /*request*/, ::mapper::MapperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* start_mapper(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_start_mapper : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_start_mapper() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mapper::MapperRequest, ::mapper::MapperReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mapper::MapperRequest, ::mapper::MapperReply>* streamer) {
                       return this->Streamedstart_mapper(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_start_mapper() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status start_mapper(::grpc::ServerContext* /*context*/, const ::mapper::MapperRequest* /*request*/, ::mapper::MapperReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedstart_mapper(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mapper::MapperRequest,::mapper::MapperReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_start_mapper<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_start_mapper<Service > StreamedService;
};

}  // namespace mapper


#endif  // GRPC_mapper_2eproto__INCLUDED
