// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mapper.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mapper_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mapper_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mapper_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mapper_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mapper_2eproto;
namespace mapper {
class MapperReply;
struct MapperReplyDefaultTypeInternal;
extern MapperReplyDefaultTypeInternal _MapperReply_default_instance_;
class MapperRequest;
struct MapperRequestDefaultTypeInternal;
extern MapperRequestDefaultTypeInternal _MapperRequest_default_instance_;
}  // namespace mapper
PROTOBUF_NAMESPACE_OPEN
template<> ::mapper::MapperReply* Arena::CreateMaybeMessage<::mapper::MapperReply>(Arena*);
template<> ::mapper::MapperRequest* Arena::CreateMaybeMessage<::mapper::MapperRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mapper {

// ===================================================================

class MapperRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mapper.MapperRequest) */ {
 public:
  inline MapperRequest() : MapperRequest(nullptr) {}
  ~MapperRequest() override;
  explicit PROTOBUF_CONSTEXPR MapperRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MapperRequest(const MapperRequest& from);
  MapperRequest(MapperRequest&& from) noexcept
    : MapperRequest() {
    *this = ::std::move(from);
  }

  inline MapperRequest& operator=(const MapperRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapperRequest& operator=(MapperRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MapperRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const MapperRequest* internal_default_instance() {
    return reinterpret_cast<const MapperRequest*>(
               &_MapperRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MapperRequest& a, MapperRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(MapperRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MapperRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MapperRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MapperRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MapperRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MapperRequest& from) {
    MapperRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapperRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mapper.MapperRequest";
  }
  protected:
  explicit MapperRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApplicationFieldNumber = 1,
    kChunkFieldNumber = 3,
    kStartlineFieldNumber = 4,
    kArgsFieldNumber = 5,
    kThreadsFieldNumber = 2,
    kIdFieldNumber = 6,
  };
  // string application = 1;
  void clear_application();
  const std::string& application() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_application(ArgT0&& arg0, ArgT... args);
  std::string* mutable_application();
  PROTOBUF_NODISCARD std::string* release_application();
  void set_allocated_application(std::string* application);
  private:
  const std::string& _internal_application() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_application(const std::string& value);
  std::string* _internal_mutable_application();
  public:

  // string chunk = 3;
  void clear_chunk();
  const std::string& chunk() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_chunk(ArgT0&& arg0, ArgT... args);
  std::string* mutable_chunk();
  PROTOBUF_NODISCARD std::string* release_chunk();
  void set_allocated_chunk(std::string* chunk);
  private:
  const std::string& _internal_chunk() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_chunk(const std::string& value);
  std::string* _internal_mutable_chunk();
  public:

  // string startline = 4;
  void clear_startline();
  const std::string& startline() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_startline(ArgT0&& arg0, ArgT... args);
  std::string* mutable_startline();
  PROTOBUF_NODISCARD std::string* release_startline();
  void set_allocated_startline(std::string* startline);
  private:
  const std::string& _internal_startline() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_startline(const std::string& value);
  std::string* _internal_mutable_startline();
  public:

  // string args = 5;
  void clear_args();
  const std::string& args() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_args(ArgT0&& arg0, ArgT... args);
  std::string* mutable_args();
  PROTOBUF_NODISCARD std::string* release_args();
  void set_allocated_args(std::string* args);
  private:
  const std::string& _internal_args() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_args(const std::string& value);
  std::string* _internal_mutable_args();
  public:

  // int32 threads = 2;
  void clear_threads();
  int32_t threads() const;
  void set_threads(int32_t value);
  private:
  int32_t _internal_threads() const;
  void _internal_set_threads(int32_t value);
  public:

  // int32 id = 6;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:mapper.MapperRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr application_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr chunk_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr startline_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr args_;
    int32_t threads_;
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mapper_2eproto;
};
// -------------------------------------------------------------------

class MapperReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mapper.MapperReply) */ {
 public:
  inline MapperReply() : MapperReply(nullptr) {}
  ~MapperReply() override;
  explicit PROTOBUF_CONSTEXPR MapperReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MapperReply(const MapperReply& from);
  MapperReply(MapperReply&& from) noexcept
    : MapperReply() {
    *this = ::std::move(from);
  }

  inline MapperReply& operator=(const MapperReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapperReply& operator=(MapperReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MapperReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const MapperReply* internal_default_instance() {
    return reinterpret_cast<const MapperReply*>(
               &_MapperReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MapperReply& a, MapperReply& b) {
    a.Swap(&b);
  }
  inline void Swap(MapperReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MapperReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MapperReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MapperReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MapperReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MapperReply& from) {
    MapperReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapperReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mapper.MapperReply";
  }
  protected:
  explicit MapperReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // int32 result = 1;
  void clear_result();
  int32_t result() const;
  void set_result(int32_t value);
  private:
  int32_t _internal_result() const;
  void _internal_set_result(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:mapper.MapperReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_mapper_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MapperRequest

// string application = 1;
inline void MapperRequest::clear_application() {
  _impl_.application_.ClearToEmpty();
}
inline const std::string& MapperRequest::application() const {
  // @@protoc_insertion_point(field_get:mapper.MapperRequest.application)
  return _internal_application();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MapperRequest::set_application(ArgT0&& arg0, ArgT... args) {
 
 _impl_.application_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mapper.MapperRequest.application)
}
inline std::string* MapperRequest::mutable_application() {
  std::string* _s = _internal_mutable_application();
  // @@protoc_insertion_point(field_mutable:mapper.MapperRequest.application)
  return _s;
}
inline const std::string& MapperRequest::_internal_application() const {
  return _impl_.application_.Get();
}
inline void MapperRequest::_internal_set_application(const std::string& value) {
  
  _impl_.application_.Set(value, GetArenaForAllocation());
}
inline std::string* MapperRequest::_internal_mutable_application() {
  
  return _impl_.application_.Mutable(GetArenaForAllocation());
}
inline std::string* MapperRequest::release_application() {
  // @@protoc_insertion_point(field_release:mapper.MapperRequest.application)
  return _impl_.application_.Release();
}
inline void MapperRequest::set_allocated_application(std::string* application) {
  if (application != nullptr) {
    
  } else {
    
  }
  _impl_.application_.SetAllocated(application, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.application_.IsDefault()) {
    _impl_.application_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mapper.MapperRequest.application)
}

// int32 threads = 2;
inline void MapperRequest::clear_threads() {
  _impl_.threads_ = 0;
}
inline int32_t MapperRequest::_internal_threads() const {
  return _impl_.threads_;
}
inline int32_t MapperRequest::threads() const {
  // @@protoc_insertion_point(field_get:mapper.MapperRequest.threads)
  return _internal_threads();
}
inline void MapperRequest::_internal_set_threads(int32_t value) {
  
  _impl_.threads_ = value;
}
inline void MapperRequest::set_threads(int32_t value) {
  _internal_set_threads(value);
  // @@protoc_insertion_point(field_set:mapper.MapperRequest.threads)
}

// string chunk = 3;
inline void MapperRequest::clear_chunk() {
  _impl_.chunk_.ClearToEmpty();
}
inline const std::string& MapperRequest::chunk() const {
  // @@protoc_insertion_point(field_get:mapper.MapperRequest.chunk)
  return _internal_chunk();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MapperRequest::set_chunk(ArgT0&& arg0, ArgT... args) {
 
 _impl_.chunk_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mapper.MapperRequest.chunk)
}
inline std::string* MapperRequest::mutable_chunk() {
  std::string* _s = _internal_mutable_chunk();
  // @@protoc_insertion_point(field_mutable:mapper.MapperRequest.chunk)
  return _s;
}
inline const std::string& MapperRequest::_internal_chunk() const {
  return _impl_.chunk_.Get();
}
inline void MapperRequest::_internal_set_chunk(const std::string& value) {
  
  _impl_.chunk_.Set(value, GetArenaForAllocation());
}
inline std::string* MapperRequest::_internal_mutable_chunk() {
  
  return _impl_.chunk_.Mutable(GetArenaForAllocation());
}
inline std::string* MapperRequest::release_chunk() {
  // @@protoc_insertion_point(field_release:mapper.MapperRequest.chunk)
  return _impl_.chunk_.Release();
}
inline void MapperRequest::set_allocated_chunk(std::string* chunk) {
  if (chunk != nullptr) {
    
  } else {
    
  }
  _impl_.chunk_.SetAllocated(chunk, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.chunk_.IsDefault()) {
    _impl_.chunk_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mapper.MapperRequest.chunk)
}

// string startline = 4;
inline void MapperRequest::clear_startline() {
  _impl_.startline_.ClearToEmpty();
}
inline const std::string& MapperRequest::startline() const {
  // @@protoc_insertion_point(field_get:mapper.MapperRequest.startline)
  return _internal_startline();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MapperRequest::set_startline(ArgT0&& arg0, ArgT... args) {
 
 _impl_.startline_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mapper.MapperRequest.startline)
}
inline std::string* MapperRequest::mutable_startline() {
  std::string* _s = _internal_mutable_startline();
  // @@protoc_insertion_point(field_mutable:mapper.MapperRequest.startline)
  return _s;
}
inline const std::string& MapperRequest::_internal_startline() const {
  return _impl_.startline_.Get();
}
inline void MapperRequest::_internal_set_startline(const std::string& value) {
  
  _impl_.startline_.Set(value, GetArenaForAllocation());
}
inline std::string* MapperRequest::_internal_mutable_startline() {
  
  return _impl_.startline_.Mutable(GetArenaForAllocation());
}
inline std::string* MapperRequest::release_startline() {
  // @@protoc_insertion_point(field_release:mapper.MapperRequest.startline)
  return _impl_.startline_.Release();
}
inline void MapperRequest::set_allocated_startline(std::string* startline) {
  if (startline != nullptr) {
    
  } else {
    
  }
  _impl_.startline_.SetAllocated(startline, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.startline_.IsDefault()) {
    _impl_.startline_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mapper.MapperRequest.startline)
}

// string args = 5;
inline void MapperRequest::clear_args() {
  _impl_.args_.ClearToEmpty();
}
inline const std::string& MapperRequest::args() const {
  // @@protoc_insertion_point(field_get:mapper.MapperRequest.args)
  return _internal_args();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MapperRequest::set_args(ArgT0&& arg0, ArgT... args) {
 
 _impl_.args_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:mapper.MapperRequest.args)
}
inline std::string* MapperRequest::mutable_args() {
  std::string* _s = _internal_mutable_args();
  // @@protoc_insertion_point(field_mutable:mapper.MapperRequest.args)
  return _s;
}
inline const std::string& MapperRequest::_internal_args() const {
  return _impl_.args_.Get();
}
inline void MapperRequest::_internal_set_args(const std::string& value) {
  
  _impl_.args_.Set(value, GetArenaForAllocation());
}
inline std::string* MapperRequest::_internal_mutable_args() {
  
  return _impl_.args_.Mutable(GetArenaForAllocation());
}
inline std::string* MapperRequest::release_args() {
  // @@protoc_insertion_point(field_release:mapper.MapperRequest.args)
  return _impl_.args_.Release();
}
inline void MapperRequest::set_allocated_args(std::string* args) {
  if (args != nullptr) {
    
  } else {
    
  }
  _impl_.args_.SetAllocated(args, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.args_.IsDefault()) {
    _impl_.args_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:mapper.MapperRequest.args)
}

// int32 id = 6;
inline void MapperRequest::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t MapperRequest::_internal_id() const {
  return _impl_.id_;
}
inline int32_t MapperRequest::id() const {
  // @@protoc_insertion_point(field_get:mapper.MapperRequest.id)
  return _internal_id();
}
inline void MapperRequest::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void MapperRequest::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:mapper.MapperRequest.id)
}

// -------------------------------------------------------------------

// MapperReply

// int32 result = 1;
inline void MapperReply::clear_result() {
  _impl_.result_ = 0;
}
inline int32_t MapperReply::_internal_result() const {
  return _impl_.result_;
}
inline int32_t MapperReply::result() const {
  // @@protoc_insertion_point(field_get:mapper.MapperReply.result)
  return _internal_result();
}
inline void MapperReply::_internal_set_result(int32_t value) {
  
  _impl_.result_ = value;
}
inline void MapperReply::set_result(int32_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:mapper.MapperReply.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mapper

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mapper_2eproto
