// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reducer.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_reducer_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_reducer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_reducer_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_reducer_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_reducer_2eproto;
namespace reducer {
class ReducerServiceFlushReply;
struct ReducerServiceFlushReplyDefaultTypeInternal;
extern ReducerServiceFlushReplyDefaultTypeInternal _ReducerServiceFlushReply_default_instance_;
class ReducerServiceFlushRequest;
struct ReducerServiceFlushRequestDefaultTypeInternal;
extern ReducerServiceFlushRequestDefaultTypeInternal _ReducerServiceFlushRequest_default_instance_;
class ReducerServiceStartReply;
struct ReducerServiceStartReplyDefaultTypeInternal;
extern ReducerServiceStartReplyDefaultTypeInternal _ReducerServiceStartReply_default_instance_;
class ReducerServiceStartRequest;
struct ReducerServiceStartRequestDefaultTypeInternal;
extern ReducerServiceStartRequestDefaultTypeInternal _ReducerServiceStartRequest_default_instance_;
}  // namespace reducer
PROTOBUF_NAMESPACE_OPEN
template<> ::reducer::ReducerServiceFlushReply* Arena::CreateMaybeMessage<::reducer::ReducerServiceFlushReply>(Arena*);
template<> ::reducer::ReducerServiceFlushRequest* Arena::CreateMaybeMessage<::reducer::ReducerServiceFlushRequest>(Arena*);
template<> ::reducer::ReducerServiceStartReply* Arena::CreateMaybeMessage<::reducer::ReducerServiceStartReply>(Arena*);
template<> ::reducer::ReducerServiceStartRequest* Arena::CreateMaybeMessage<::reducer::ReducerServiceStartRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace reducer {

// ===================================================================

class ReducerServiceStartRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:reducer.ReducerServiceStartRequest) */ {
 public:
  inline ReducerServiceStartRequest() : ReducerServiceStartRequest(nullptr) {}
  ~ReducerServiceStartRequest() override;
  explicit PROTOBUF_CONSTEXPR ReducerServiceStartRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReducerServiceStartRequest(const ReducerServiceStartRequest& from);
  ReducerServiceStartRequest(ReducerServiceStartRequest&& from) noexcept
    : ReducerServiceStartRequest() {
    *this = ::std::move(from);
  }

  inline ReducerServiceStartRequest& operator=(const ReducerServiceStartRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReducerServiceStartRequest& operator=(ReducerServiceStartRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReducerServiceStartRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReducerServiceStartRequest* internal_default_instance() {
    return reinterpret_cast<const ReducerServiceStartRequest*>(
               &_ReducerServiceStartRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ReducerServiceStartRequest& a, ReducerServiceStartRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ReducerServiceStartRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReducerServiceStartRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReducerServiceStartRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReducerServiceStartRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReducerServiceStartRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReducerServiceStartRequest& from) {
    ReducerServiceStartRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReducerServiceStartRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "reducer.ReducerServiceStartRequest";
  }
  protected:
  explicit ReducerServiceStartRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApplicationFieldNumber = 1,
    kOutpathFieldNumber = 3,
    kThreadsFieldNumber = 2,
    kBarrierFieldNumber = 4,
    kIdFieldNumber = 5,
  };
  // string application = 1;
  void clear_application();
  const std::string& application() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_application(ArgT0&& arg0, ArgT... args);
  std::string* mutable_application();
  PROTOBUF_NODISCARD std::string* release_application();
  void set_allocated_application(std::string* application);
  private:
  const std::string& _internal_application() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_application(const std::string& value);
  std::string* _internal_mutable_application();
  public:

  // string outpath = 3;
  void clear_outpath();
  const std::string& outpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_outpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_outpath();
  PROTOBUF_NODISCARD std::string* release_outpath();
  void set_allocated_outpath(std::string* outpath);
  private:
  const std::string& _internal_outpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_outpath(const std::string& value);
  std::string* _internal_mutable_outpath();
  public:

  // int32 threads = 2;
  void clear_threads();
  int32_t threads() const;
  void set_threads(int32_t value);
  private:
  int32_t _internal_threads() const;
  void _internal_set_threads(int32_t value);
  public:

  // int32 barrier = 4;
  void clear_barrier();
  int32_t barrier() const;
  void set_barrier(int32_t value);
  private:
  int32_t _internal_barrier() const;
  void _internal_set_barrier(int32_t value);
  public:

  // int32 id = 5;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:reducer.ReducerServiceStartRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr application_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr outpath_;
    int32_t threads_;
    int32_t barrier_;
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_reducer_2eproto;
};
// -------------------------------------------------------------------

class ReducerServiceStartReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:reducer.ReducerServiceStartReply) */ {
 public:
  inline ReducerServiceStartReply() : ReducerServiceStartReply(nullptr) {}
  ~ReducerServiceStartReply() override;
  explicit PROTOBUF_CONSTEXPR ReducerServiceStartReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReducerServiceStartReply(const ReducerServiceStartReply& from);
  ReducerServiceStartReply(ReducerServiceStartReply&& from) noexcept
    : ReducerServiceStartReply() {
    *this = ::std::move(from);
  }

  inline ReducerServiceStartReply& operator=(const ReducerServiceStartReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReducerServiceStartReply& operator=(ReducerServiceStartReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReducerServiceStartReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReducerServiceStartReply* internal_default_instance() {
    return reinterpret_cast<const ReducerServiceStartReply*>(
               &_ReducerServiceStartReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ReducerServiceStartReply& a, ReducerServiceStartReply& b) {
    a.Swap(&b);
  }
  inline void Swap(ReducerServiceStartReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReducerServiceStartReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReducerServiceStartReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReducerServiceStartReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReducerServiceStartReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReducerServiceStartReply& from) {
    ReducerServiceStartReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReducerServiceStartReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "reducer.ReducerServiceStartReply";
  }
  protected:
  explicit ReducerServiceStartReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // int32 result = 1;
  void clear_result();
  int32_t result() const;
  void set_result(int32_t value);
  private:
  int32_t _internal_result() const;
  void _internal_set_result(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:reducer.ReducerServiceStartReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_reducer_2eproto;
};
// -------------------------------------------------------------------

class ReducerServiceFlushRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:reducer.ReducerServiceFlushRequest) */ {
 public:
  inline ReducerServiceFlushRequest() : ReducerServiceFlushRequest(nullptr) {}
  ~ReducerServiceFlushRequest() override;
  explicit PROTOBUF_CONSTEXPR ReducerServiceFlushRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReducerServiceFlushRequest(const ReducerServiceFlushRequest& from);
  ReducerServiceFlushRequest(ReducerServiceFlushRequest&& from) noexcept
    : ReducerServiceFlushRequest() {
    *this = ::std::move(from);
  }

  inline ReducerServiceFlushRequest& operator=(const ReducerServiceFlushRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReducerServiceFlushRequest& operator=(ReducerServiceFlushRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReducerServiceFlushRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReducerServiceFlushRequest* internal_default_instance() {
    return reinterpret_cast<const ReducerServiceFlushRequest*>(
               &_ReducerServiceFlushRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ReducerServiceFlushRequest& a, ReducerServiceFlushRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ReducerServiceFlushRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReducerServiceFlushRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReducerServiceFlushRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReducerServiceFlushRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReducerServiceFlushRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReducerServiceFlushRequest& from) {
    ReducerServiceFlushRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReducerServiceFlushRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "reducer.ReducerServiceFlushRequest";
  }
  protected:
  explicit ReducerServiceFlushRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBufferFieldNumber = 2,
    kIdFieldNumber = 1,
    kSizeFieldNumber = 3,
  };
  // bytes buffer = 2;
  void clear_buffer();
  const std::string& buffer() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_buffer(ArgT0&& arg0, ArgT... args);
  std::string* mutable_buffer();
  PROTOBUF_NODISCARD std::string* release_buffer();
  void set_allocated_buffer(std::string* buffer);
  private:
  const std::string& _internal_buffer() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_buffer(const std::string& value);
  std::string* _internal_mutable_buffer();
  public:

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // int32 size = 3;
  void clear_size();
  int32_t size() const;
  void set_size(int32_t value);
  private:
  int32_t _internal_size() const;
  void _internal_set_size(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:reducer.ReducerServiceFlushRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr buffer_;
    int32_t id_;
    int32_t size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_reducer_2eproto;
};
// -------------------------------------------------------------------

class ReducerServiceFlushReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:reducer.ReducerServiceFlushReply) */ {
 public:
  inline ReducerServiceFlushReply() : ReducerServiceFlushReply(nullptr) {}
  ~ReducerServiceFlushReply() override;
  explicit PROTOBUF_CONSTEXPR ReducerServiceFlushReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReducerServiceFlushReply(const ReducerServiceFlushReply& from);
  ReducerServiceFlushReply(ReducerServiceFlushReply&& from) noexcept
    : ReducerServiceFlushReply() {
    *this = ::std::move(from);
  }

  inline ReducerServiceFlushReply& operator=(const ReducerServiceFlushReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReducerServiceFlushReply& operator=(ReducerServiceFlushReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReducerServiceFlushReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReducerServiceFlushReply* internal_default_instance() {
    return reinterpret_cast<const ReducerServiceFlushReply*>(
               &_ReducerServiceFlushReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ReducerServiceFlushReply& a, ReducerServiceFlushReply& b) {
    a.Swap(&b);
  }
  inline void Swap(ReducerServiceFlushReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReducerServiceFlushReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReducerServiceFlushReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReducerServiceFlushReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReducerServiceFlushReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReducerServiceFlushReply& from) {
    ReducerServiceFlushReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReducerServiceFlushReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "reducer.ReducerServiceFlushReply";
  }
  protected:
  explicit ReducerServiceFlushReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessfulFieldNumber = 1,
  };
  // int32 successful = 1;
  void clear_successful();
  int32_t successful() const;
  void set_successful(int32_t value);
  private:
  int32_t _internal_successful() const;
  void _internal_set_successful(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:reducer.ReducerServiceFlushReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t successful_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_reducer_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReducerServiceStartRequest

// string application = 1;
inline void ReducerServiceStartRequest::clear_application() {
  _impl_.application_.ClearToEmpty();
}
inline const std::string& ReducerServiceStartRequest::application() const {
  // @@protoc_insertion_point(field_get:reducer.ReducerServiceStartRequest.application)
  return _internal_application();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReducerServiceStartRequest::set_application(ArgT0&& arg0, ArgT... args) {
 
 _impl_.application_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:reducer.ReducerServiceStartRequest.application)
}
inline std::string* ReducerServiceStartRequest::mutable_application() {
  std::string* _s = _internal_mutable_application();
  // @@protoc_insertion_point(field_mutable:reducer.ReducerServiceStartRequest.application)
  return _s;
}
inline const std::string& ReducerServiceStartRequest::_internal_application() const {
  return _impl_.application_.Get();
}
inline void ReducerServiceStartRequest::_internal_set_application(const std::string& value) {
  
  _impl_.application_.Set(value, GetArenaForAllocation());
}
inline std::string* ReducerServiceStartRequest::_internal_mutable_application() {
  
  return _impl_.application_.Mutable(GetArenaForAllocation());
}
inline std::string* ReducerServiceStartRequest::release_application() {
  // @@protoc_insertion_point(field_release:reducer.ReducerServiceStartRequest.application)
  return _impl_.application_.Release();
}
inline void ReducerServiceStartRequest::set_allocated_application(std::string* application) {
  if (application != nullptr) {
    
  } else {
    
  }
  _impl_.application_.SetAllocated(application, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.application_.IsDefault()) {
    _impl_.application_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:reducer.ReducerServiceStartRequest.application)
}

// int32 threads = 2;
inline void ReducerServiceStartRequest::clear_threads() {
  _impl_.threads_ = 0;
}
inline int32_t ReducerServiceStartRequest::_internal_threads() const {
  return _impl_.threads_;
}
inline int32_t ReducerServiceStartRequest::threads() const {
  // @@protoc_insertion_point(field_get:reducer.ReducerServiceStartRequest.threads)
  return _internal_threads();
}
inline void ReducerServiceStartRequest::_internal_set_threads(int32_t value) {
  
  _impl_.threads_ = value;
}
inline void ReducerServiceStartRequest::set_threads(int32_t value) {
  _internal_set_threads(value);
  // @@protoc_insertion_point(field_set:reducer.ReducerServiceStartRequest.threads)
}

// string outpath = 3;
inline void ReducerServiceStartRequest::clear_outpath() {
  _impl_.outpath_.ClearToEmpty();
}
inline const std::string& ReducerServiceStartRequest::outpath() const {
  // @@protoc_insertion_point(field_get:reducer.ReducerServiceStartRequest.outpath)
  return _internal_outpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReducerServiceStartRequest::set_outpath(ArgT0&& arg0, ArgT... args) {
 
 _impl_.outpath_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:reducer.ReducerServiceStartRequest.outpath)
}
inline std::string* ReducerServiceStartRequest::mutable_outpath() {
  std::string* _s = _internal_mutable_outpath();
  // @@protoc_insertion_point(field_mutable:reducer.ReducerServiceStartRequest.outpath)
  return _s;
}
inline const std::string& ReducerServiceStartRequest::_internal_outpath() const {
  return _impl_.outpath_.Get();
}
inline void ReducerServiceStartRequest::_internal_set_outpath(const std::string& value) {
  
  _impl_.outpath_.Set(value, GetArenaForAllocation());
}
inline std::string* ReducerServiceStartRequest::_internal_mutable_outpath() {
  
  return _impl_.outpath_.Mutable(GetArenaForAllocation());
}
inline std::string* ReducerServiceStartRequest::release_outpath() {
  // @@protoc_insertion_point(field_release:reducer.ReducerServiceStartRequest.outpath)
  return _impl_.outpath_.Release();
}
inline void ReducerServiceStartRequest::set_allocated_outpath(std::string* outpath) {
  if (outpath != nullptr) {
    
  } else {
    
  }
  _impl_.outpath_.SetAllocated(outpath, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.outpath_.IsDefault()) {
    _impl_.outpath_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:reducer.ReducerServiceStartRequest.outpath)
}

// int32 barrier = 4;
inline void ReducerServiceStartRequest::clear_barrier() {
  _impl_.barrier_ = 0;
}
inline int32_t ReducerServiceStartRequest::_internal_barrier() const {
  return _impl_.barrier_;
}
inline int32_t ReducerServiceStartRequest::barrier() const {
  // @@protoc_insertion_point(field_get:reducer.ReducerServiceStartRequest.barrier)
  return _internal_barrier();
}
inline void ReducerServiceStartRequest::_internal_set_barrier(int32_t value) {
  
  _impl_.barrier_ = value;
}
inline void ReducerServiceStartRequest::set_barrier(int32_t value) {
  _internal_set_barrier(value);
  // @@protoc_insertion_point(field_set:reducer.ReducerServiceStartRequest.barrier)
}

// int32 id = 5;
inline void ReducerServiceStartRequest::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t ReducerServiceStartRequest::_internal_id() const {
  return _impl_.id_;
}
inline int32_t ReducerServiceStartRequest::id() const {
  // @@protoc_insertion_point(field_get:reducer.ReducerServiceStartRequest.id)
  return _internal_id();
}
inline void ReducerServiceStartRequest::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void ReducerServiceStartRequest::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:reducer.ReducerServiceStartRequest.id)
}

// -------------------------------------------------------------------

// ReducerServiceStartReply

// int32 result = 1;
inline void ReducerServiceStartReply::clear_result() {
  _impl_.result_ = 0;
}
inline int32_t ReducerServiceStartReply::_internal_result() const {
  return _impl_.result_;
}
inline int32_t ReducerServiceStartReply::result() const {
  // @@protoc_insertion_point(field_get:reducer.ReducerServiceStartReply.result)
  return _internal_result();
}
inline void ReducerServiceStartReply::_internal_set_result(int32_t value) {
  
  _impl_.result_ = value;
}
inline void ReducerServiceStartReply::set_result(int32_t value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:reducer.ReducerServiceStartReply.result)
}

// -------------------------------------------------------------------

// ReducerServiceFlushRequest

// int32 id = 1;
inline void ReducerServiceFlushRequest::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t ReducerServiceFlushRequest::_internal_id() const {
  return _impl_.id_;
}
inline int32_t ReducerServiceFlushRequest::id() const {
  // @@protoc_insertion_point(field_get:reducer.ReducerServiceFlushRequest.id)
  return _internal_id();
}
inline void ReducerServiceFlushRequest::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void ReducerServiceFlushRequest::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:reducer.ReducerServiceFlushRequest.id)
}

// bytes buffer = 2;
inline void ReducerServiceFlushRequest::clear_buffer() {
  _impl_.buffer_.ClearToEmpty();
}
inline const std::string& ReducerServiceFlushRequest::buffer() const {
  // @@protoc_insertion_point(field_get:reducer.ReducerServiceFlushRequest.buffer)
  return _internal_buffer();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReducerServiceFlushRequest::set_buffer(ArgT0&& arg0, ArgT... args) {
 
 _impl_.buffer_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:reducer.ReducerServiceFlushRequest.buffer)
}
inline std::string* ReducerServiceFlushRequest::mutable_buffer() {
  std::string* _s = _internal_mutable_buffer();
  // @@protoc_insertion_point(field_mutable:reducer.ReducerServiceFlushRequest.buffer)
  return _s;
}
inline const std::string& ReducerServiceFlushRequest::_internal_buffer() const {
  return _impl_.buffer_.Get();
}
inline void ReducerServiceFlushRequest::_internal_set_buffer(const std::string& value) {
  
  _impl_.buffer_.Set(value, GetArenaForAllocation());
}
inline std::string* ReducerServiceFlushRequest::_internal_mutable_buffer() {
  
  return _impl_.buffer_.Mutable(GetArenaForAllocation());
}
inline std::string* ReducerServiceFlushRequest::release_buffer() {
  // @@protoc_insertion_point(field_release:reducer.ReducerServiceFlushRequest.buffer)
  return _impl_.buffer_.Release();
}
inline void ReducerServiceFlushRequest::set_allocated_buffer(std::string* buffer) {
  if (buffer != nullptr) {
    
  } else {
    
  }
  _impl_.buffer_.SetAllocated(buffer, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.buffer_.IsDefault()) {
    _impl_.buffer_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:reducer.ReducerServiceFlushRequest.buffer)
}

// int32 size = 3;
inline void ReducerServiceFlushRequest::clear_size() {
  _impl_.size_ = 0;
}
inline int32_t ReducerServiceFlushRequest::_internal_size() const {
  return _impl_.size_;
}
inline int32_t ReducerServiceFlushRequest::size() const {
  // @@protoc_insertion_point(field_get:reducer.ReducerServiceFlushRequest.size)
  return _internal_size();
}
inline void ReducerServiceFlushRequest::_internal_set_size(int32_t value) {
  
  _impl_.size_ = value;
}
inline void ReducerServiceFlushRequest::set_size(int32_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:reducer.ReducerServiceFlushRequest.size)
}

// -------------------------------------------------------------------

// ReducerServiceFlushReply

// int32 successful = 1;
inline void ReducerServiceFlushReply::clear_successful() {
  _impl_.successful_ = 0;
}
inline int32_t ReducerServiceFlushReply::_internal_successful() const {
  return _impl_.successful_;
}
inline int32_t ReducerServiceFlushReply::successful() const {
  // @@protoc_insertion_point(field_get:reducer.ReducerServiceFlushReply.successful)
  return _internal_successful();
}
inline void ReducerServiceFlushReply::_internal_set_successful(int32_t value) {
  
  _impl_.successful_ = value;
}
inline void ReducerServiceFlushReply::set_successful(int32_t value) {
  _internal_set_successful(value);
  // @@protoc_insertion_point(field_set:reducer.ReducerServiceFlushReply.successful)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace reducer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_reducer_2eproto
