// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: reducer.proto
#ifndef GRPC_reducer_2eproto__INCLUDED
#define GRPC_reducer_2eproto__INCLUDED

#include "reducer.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace reducer {

// Defines the service
class Reducer final {
 public:
  static constexpr char const* service_full_name() {
    return "reducer.Reducer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Function invoked to send the request
    virtual ::grpc::Status start_reducer(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest& request, ::reducer::ReducerServiceStartReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceStartReply>> Asyncstart_reducer(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceStartReply>>(Asyncstart_reducerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceStartReply>> PrepareAsyncstart_reducer(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceStartReply>>(PrepareAsyncstart_reducerRaw(context, request, cq));
    }
    virtual ::grpc::Status flush(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest& request, ::reducer::ReducerServiceFlushReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceFlushReply>> Asyncflush(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceFlushReply>>(AsyncflushRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceFlushReply>> PrepareAsyncflush(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceFlushReply>>(PrepareAsyncflushRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Function invoked to send the request
      virtual void start_reducer(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest* request, ::reducer::ReducerServiceStartReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void start_reducer(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest* request, ::reducer::ReducerServiceStartReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void flush(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest* request, ::reducer::ReducerServiceFlushReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void flush(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest* request, ::reducer::ReducerServiceFlushReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceStartReply>* Asyncstart_reducerRaw(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceStartReply>* PrepareAsyncstart_reducerRaw(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceFlushReply>* AsyncflushRaw(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::reducer::ReducerServiceFlushReply>* PrepareAsyncflushRaw(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status start_reducer(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest& request, ::reducer::ReducerServiceStartReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceStartReply>> Asyncstart_reducer(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceStartReply>>(Asyncstart_reducerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceStartReply>> PrepareAsyncstart_reducer(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceStartReply>>(PrepareAsyncstart_reducerRaw(context, request, cq));
    }
    ::grpc::Status flush(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest& request, ::reducer::ReducerServiceFlushReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceFlushReply>> Asyncflush(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceFlushReply>>(AsyncflushRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceFlushReply>> PrepareAsyncflush(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceFlushReply>>(PrepareAsyncflushRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void start_reducer(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest* request, ::reducer::ReducerServiceStartReply* response, std::function<void(::grpc::Status)>) override;
      void start_reducer(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest* request, ::reducer::ReducerServiceStartReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void flush(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest* request, ::reducer::ReducerServiceFlushReply* response, std::function<void(::grpc::Status)>) override;
      void flush(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest* request, ::reducer::ReducerServiceFlushReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceStartReply>* Asyncstart_reducerRaw(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceStartReply>* PrepareAsyncstart_reducerRaw(::grpc::ClientContext* context, const ::reducer::ReducerServiceStartRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceFlushReply>* AsyncflushRaw(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::reducer::ReducerServiceFlushReply>* PrepareAsyncflushRaw(::grpc::ClientContext* context, const ::reducer::ReducerServiceFlushRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_start_reducer_;
    const ::grpc::internal::RpcMethod rpcmethod_flush_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Function invoked to send the request
    virtual ::grpc::Status start_reducer(::grpc::ServerContext* context, const ::reducer::ReducerServiceStartRequest* request, ::reducer::ReducerServiceStartReply* response);
    virtual ::grpc::Status flush(::grpc::ServerContext* context, const ::reducer::ReducerServiceFlushRequest* request, ::reducer::ReducerServiceFlushReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_start_reducer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_start_reducer() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_start_reducer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status start_reducer(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceStartRequest* /*request*/, ::reducer::ReducerServiceStartReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requeststart_reducer(::grpc::ServerContext* context, ::reducer::ReducerServiceStartRequest* request, ::grpc::ServerAsyncResponseWriter< ::reducer::ReducerServiceStartReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_flush : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_flush() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_flush() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status flush(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceFlushRequest* /*request*/, ::reducer::ReducerServiceFlushReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestflush(::grpc::ServerContext* context, ::reducer::ReducerServiceFlushRequest* request, ::grpc::ServerAsyncResponseWriter< ::reducer::ReducerServiceFlushReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_start_reducer<WithAsyncMethod_flush<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_start_reducer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_start_reducer() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::reducer::ReducerServiceStartRequest, ::reducer::ReducerServiceStartReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::reducer::ReducerServiceStartRequest* request, ::reducer::ReducerServiceStartReply* response) { return this->start_reducer(context, request, response); }));}
    void SetMessageAllocatorFor_start_reducer(
        ::grpc::MessageAllocator< ::reducer::ReducerServiceStartRequest, ::reducer::ReducerServiceStartReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::reducer::ReducerServiceStartRequest, ::reducer::ReducerServiceStartReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_start_reducer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status start_reducer(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceStartRequest* /*request*/, ::reducer::ReducerServiceStartReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* start_reducer(
      ::grpc::CallbackServerContext* /*context*/, const ::reducer::ReducerServiceStartRequest* /*request*/, ::reducer::ReducerServiceStartReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_flush : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_flush() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::reducer::ReducerServiceFlushRequest, ::reducer::ReducerServiceFlushReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::reducer::ReducerServiceFlushRequest* request, ::reducer::ReducerServiceFlushReply* response) { return this->flush(context, request, response); }));}
    void SetMessageAllocatorFor_flush(
        ::grpc::MessageAllocator< ::reducer::ReducerServiceFlushRequest, ::reducer::ReducerServiceFlushReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::reducer::ReducerServiceFlushRequest, ::reducer::ReducerServiceFlushReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_flush() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status flush(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceFlushRequest* /*request*/, ::reducer::ReducerServiceFlushReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* flush(
      ::grpc::CallbackServerContext* /*context*/, const ::reducer::ReducerServiceFlushRequest* /*request*/, ::reducer::ReducerServiceFlushReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_start_reducer<WithCallbackMethod_flush<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_start_reducer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_start_reducer() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_start_reducer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status start_reducer(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceStartRequest* /*request*/, ::reducer::ReducerServiceStartReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_flush : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_flush() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_flush() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status flush(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceFlushRequest* /*request*/, ::reducer::ReducerServiceFlushReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_start_reducer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_start_reducer() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_start_reducer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status start_reducer(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceStartRequest* /*request*/, ::reducer::ReducerServiceStartReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requeststart_reducer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_flush : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_flush() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_flush() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status flush(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceFlushRequest* /*request*/, ::reducer::ReducerServiceFlushReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestflush(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_start_reducer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_start_reducer() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->start_reducer(context, request, response); }));
    }
    ~WithRawCallbackMethod_start_reducer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status start_reducer(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceStartRequest* /*request*/, ::reducer::ReducerServiceStartReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* start_reducer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_flush : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_flush() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->flush(context, request, response); }));
    }
    ~WithRawCallbackMethod_flush() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status flush(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceFlushRequest* /*request*/, ::reducer::ReducerServiceFlushReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* flush(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_start_reducer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_start_reducer() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::reducer::ReducerServiceStartRequest, ::reducer::ReducerServiceStartReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::reducer::ReducerServiceStartRequest, ::reducer::ReducerServiceStartReply>* streamer) {
                       return this->Streamedstart_reducer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_start_reducer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status start_reducer(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceStartRequest* /*request*/, ::reducer::ReducerServiceStartReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedstart_reducer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::reducer::ReducerServiceStartRequest,::reducer::ReducerServiceStartReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_flush : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_flush() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::reducer::ReducerServiceFlushRequest, ::reducer::ReducerServiceFlushReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::reducer::ReducerServiceFlushRequest, ::reducer::ReducerServiceFlushReply>* streamer) {
                       return this->Streamedflush(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_flush() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status flush(::grpc::ServerContext* /*context*/, const ::reducer::ReducerServiceFlushRequest* /*request*/, ::reducer::ReducerServiceFlushReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedflush(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::reducer::ReducerServiceFlushRequest,::reducer::ReducerServiceFlushReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_start_reducer<WithStreamedUnaryMethod_flush<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_start_reducer<WithStreamedUnaryMethod_flush<Service > > StreamedService;
};

}  // namespace reducer


#endif  // GRPC_reducer_2eproto__INCLUDED
